using System.Runtime.InteropServices;
using UnityEngine;
using UnityEngine.InputSystem.Layouts;
using UnityEngine.InputSystem.LowLevel;
using UnityEngine.InputSystem.Utilities;

namespace NewBlood
{
	[StructLayout(LayoutKind.Sequential, Pack = 1)]
	internal struct LegacyInputState : IInputStateTypeInfo
	{
		private static readonly KeyCode[] s_BitKeys;

		[InputControl(name = "backspace", layout = "Button", bit = 0u)]
		[InputControl(name = "tab", layout = "Button", bit = 1u)]
		[InputControl(name = "clear", layout = "Button", bit = 2u)]
		[InputControl(name = "return", layout = "Button", bit = 3u)]
		[InputControl(name = "pause", layout = "Button", bit = 4u)]
		[InputControl(name = "escape", layout = "Button", bit = 5u)]
		[InputControl(name = "space", layout = "Button", bit = 6u)]
		[InputControl(name = "exclaim", layout = "Button", bit = 7u)]
		[InputControl(name = "doubleQuote", layout = "Button", bit = 8u)]
		[InputControl(name = "hash", layout = "Button", bit = 9u)]
		[InputControl(name = "dollar", layout = "Button", bit = 10u)]
		[InputControl(name = "percent", layout = "Button", bit = 11u)]
		[InputControl(name = "ampersand", layout = "Button", bit = 12u)]
		[InputControl(name = "quote", layout = "Button", bit = 13u)]
		[InputControl(name = "leftParen", layout = "Button", bit = 14u)]
		[InputControl(name = "rightParen", layout = "Button", bit = 15u)]
		[InputControl(name = "asterisk", layout = "Button", bit = 16u)]
		[InputControl(name = "plus", layout = "Button", bit = 17u)]
		[InputControl(name = "comma", layout = "Button", bit = 18u)]
		[InputControl(name = "minus", layout = "Button", bit = 19u)]
		[InputControl(name = "period", layout = "Button", bit = 20u)]
		[InputControl(name = "slash", layout = "Button", bit = 21u)]
		[InputControl(name = "alpha0", layout = "Button", bit = 22u)]
		[InputControl(name = "alpha1", layout = "Button", bit = 23u)]
		[InputControl(name = "alpha2", layout = "Button", bit = 24u)]
		[InputControl(name = "alpha3", layout = "Button", bit = 25u)]
		[InputControl(name = "alpha4", layout = "Button", bit = 26u)]
		[InputControl(name = "alpha5", layout = "Button", bit = 27u)]
		[InputControl(name = "alpha6", layout = "Button", bit = 28u)]
		[InputControl(name = "alpha7", layout = "Button", bit = 29u)]
		[InputControl(name = "alpha8", layout = "Button", bit = 30u)]
		[InputControl(name = "alpha9", layout = "Button", bit = 31u)]
		public int bits0;

		[InputControl(name = "colon", layout = "Button", bit = 0u)]
		[InputControl(name = "semicolon", layout = "Button", bit = 1u)]
		[InputControl(name = "less", layout = "Button", bit = 2u)]
		[InputControl(name = "equals", layout = "Button", bit = 3u)]
		[InputControl(name = "greater", layout = "Button", bit = 4u)]
		[InputControl(name = "question", layout = "Button", bit = 5u)]
		[InputControl(name = "at", layout = "Button", bit = 6u)]
		[InputControl(name = "leftBracket", layout = "Button", bit = 7u)]
		[InputControl(name = "backslash", layout = "Button", bit = 8u)]
		[InputControl(name = "rightBracket", layout = "Button", bit = 9u)]
		[InputControl(name = "caret", layout = "Button", bit = 10u)]
		[InputControl(name = "underscore", layout = "Button", bit = 11u)]
		[InputControl(name = "backQuote", layout = "Button", bit = 12u)]
		[InputControl(name = "a", layout = "Button", bit = 13u)]
		[InputControl(name = "b", layout = "Button", bit = 14u)]
		[InputControl(name = "c", layout = "Button", bit = 15u)]
		[InputControl(name = "d", layout = "Button", bit = 16u)]
		[InputControl(name = "e", layout = "Button", bit = 17u)]
		[InputControl(name = "f", layout = "Button", bit = 18u)]
		[InputControl(name = "g", layout = "Button", bit = 19u)]
		[InputControl(name = "h", layout = "Button", bit = 20u)]
		[InputControl(name = "i", layout = "Button", bit = 21u)]
		[InputControl(name = "j", layout = "Button", bit = 22u)]
		[InputControl(name = "k", layout = "Button", bit = 23u)]
		[InputControl(name = "l", layout = "Button", bit = 24u)]
		[InputControl(name = "m", layout = "Button", bit = 25u)]
		[InputControl(name = "n", layout = "Button", bit = 26u)]
		[InputControl(name = "o", layout = "Button", bit = 27u)]
		[InputControl(name = "p", layout = "Button", bit = 28u)]
		[InputControl(name = "q", layout = "Button", bit = 29u)]
		[InputControl(name = "r", layout = "Button", bit = 30u)]
		[InputControl(name = "s", layout = "Button", bit = 31u)]
		public int bits1;

		[InputControl(name = "t", layout = "Button", bit = 0u)]
		[InputControl(name = "u", layout = "Button", bit = 1u)]
		[InputControl(name = "v", layout = "Button", bit = 2u)]
		[InputControl(name = "w", layout = "Button", bit = 3u)]
		[InputControl(name = "x", layout = "Button", bit = 4u)]
		[InputControl(name = "y", layout = "Button", bit = 5u)]
		[InputControl(name = "z", layout = "Button", bit = 6u)]
		[InputControl(name = "leftCurlyBracket", layout = "Button", bit = 7u)]
		[InputControl(name = "pipe", layout = "Button", bit = 8u)]
		[InputControl(name = "rightCurlyBracket", layout = "Button", bit = 9u)]
		[InputControl(name = "tilde", layout = "Button", bit = 10u)]
		[InputControl(name = "delete", layout = "Button", bit = 11u)]
		[InputControl(name = "keypad0", layout = "Button", bit = 12u)]
		[InputControl(name = "keypad1", layout = "Button", bit = 13u)]
		[InputControl(name = "keypad2", layout = "Button", bit = 14u)]
		[InputControl(name = "keypad3", layout = "Button", bit = 15u)]
		[InputControl(name = "keypad4", layout = "Button", bit = 16u)]
		[InputControl(name = "keypad5", layout = "Button", bit = 17u)]
		[InputControl(name = "keypad6", layout = "Button", bit = 18u)]
		[InputControl(name = "keypad7", layout = "Button", bit = 19u)]
		[InputControl(name = "keypad8", layout = "Button", bit = 20u)]
		[InputControl(name = "keypad9", layout = "Button", bit = 21u)]
		[InputControl(name = "keypadPeriod", layout = "Button", bit = 22u)]
		[InputControl(name = "keypadDivide", layout = "Button", bit = 23u)]
		[InputControl(name = "keypadMultiply", layout = "Button", bit = 24u)]
		[InputControl(name = "keypadMinus", layout = "Button", bit = 25u)]
		[InputControl(name = "keypadPlus", layout = "Button", bit = 26u)]
		[InputControl(name = "keypadEnter", layout = "Button", bit = 27u)]
		[InputControl(name = "keypadEquals", layout = "Button", bit = 28u)]
		[InputControl(name = "upArrow", layout = "Button", bit = 29u)]
		[InputControl(name = "downArrow", layout = "Button", bit = 30u)]
		[InputControl(name = "rightArrow", layout = "Button", bit = 31u)]
		public int bits2;

		[InputControl(name = "leftArrow", layout = "Button", bit = 0u)]
		[InputControl(name = "insert", layout = "Button", bit = 1u)]
		[InputControl(name = "home", layout = "Button", bit = 2u)]
		[InputControl(name = "end", layout = "Button", bit = 3u)]
		[InputControl(name = "pageUp", layout = "Button", bit = 4u)]
		[InputControl(name = "pageDown", layout = "Button", bit = 5u)]
		[InputControl(name = "f1", layout = "Button", bit = 6u)]
		[InputControl(name = "f2", layout = "Button", bit = 7u)]
		[InputControl(name = "f3", layout = "Button", bit = 8u)]
		[InputControl(name = "f4", layout = "Button", bit = 9u)]
		[InputControl(name = "f5", layout = "Button", bit = 10u)]
		[InputControl(name = "f6", layout = "Button", bit = 11u)]
		[InputControl(name = "f7", layout = "Button", bit = 12u)]
		[InputControl(name = "f8", layout = "Button", bit = 13u)]
		[InputControl(name = "f9", layout = "Button", bit = 14u)]
		[InputControl(name = "f10", layout = "Button", bit = 15u)]
		[InputControl(name = "f11", layout = "Button", bit = 16u)]
		[InputControl(name = "f12", layout = "Button", bit = 17u)]
		[InputControl(name = "f13", layout = "Button", bit = 18u)]
		[InputControl(name = "f14", layout = "Button", bit = 19u)]
		[InputControl(name = "f15", layout = "Button", bit = 20u)]
		[InputControl(name = "numlock", layout = "Button", bit = 21u)]
		[InputControl(name = "capsLock", layout = "Button", bit = 22u)]
		[InputControl(name = "scrollLock", layout = "Button", bit = 23u)]
		[InputControl(name = "rightShift", layout = "Button", bit = 24u)]
		[InputControl(name = "leftShift", layout = "Button", bit = 25u)]
		[InputControl(name = "rightControl", layout = "Button", bit = 26u)]
		[InputControl(name = "leftControl", layout = "Button", bit = 27u)]
		[InputControl(name = "rightAlt", layout = "Button", bit = 28u)]
		[InputControl(name = "leftAlt", layout = "Button", bit = 29u)]
		[InputControl(name = "rightCommand", layout = "Button", bit = 30u)]
		[InputControl(name = "leftCommand", layout = "Button", bit = 31u)]
		public int bits3;

		[InputControl(name = "leftWindows", layout = "Button", bit = 0u)]
		[InputControl(name = "rightWindows", layout = "Button", bit = 1u)]
		[InputControl(name = "altGr", layout = "Button", bit = 2u)]
		[InputControl(name = "help", layout = "Button", bit = 3u)]
		[InputControl(name = "print", layout = "Button", bit = 4u)]
		[InputControl(name = "sysReq", layout = "Button", bit = 5u)]
		[InputControl(name = "break", layout = "Button", bit = 6u)]
		[InputControl(name = "menu", layout = "Button", bit = 7u)]
		[InputControl(name = "mouse0", layout = "Button", bit = 8u)]
		[InputControl(name = "mouse1", layout = "Button", bit = 9u)]
		[InputControl(name = "mouse2", layout = "Button", bit = 10u)]
		[InputControl(name = "mouse3", layout = "Button", bit = 11u)]
		[InputControl(name = "mouse4", layout = "Button", bit = 12u)]
		[InputControl(name = "mouse5", layout = "Button", bit = 13u)]
		[InputControl(name = "mouse6", layout = "Button", bit = 14u)]
		[InputControl(name = "joystickButton0", layout = "Button", bit = 15u)]
		[InputControl(name = "joystickButton1", layout = "Button", bit = 16u)]
		[InputControl(name = "joystickButton2", layout = "Button", bit = 17u)]
		[InputControl(name = "joystickButton3", layout = "Button", bit = 18u)]
		[InputControl(name = "joystickButton4", layout = "Button", bit = 19u)]
		[InputControl(name = "joystickButton5", layout = "Button", bit = 20u)]
		[InputControl(name = "joystickButton6", layout = "Button", bit = 21u)]
		[InputControl(name = "joystickButton7", layout = "Button", bit = 22u)]
		[InputControl(name = "joystickButton8", layout = "Button", bit = 23u)]
		[InputControl(name = "joystickButton9", layout = "Button", bit = 24u)]
		[InputControl(name = "joystickButton10", layout = "Button", bit = 25u)]
		[InputControl(name = "joystickButton11", layout = "Button", bit = 26u)]
		[InputControl(name = "joystickButton12", layout = "Button", bit = 27u)]
		[InputControl(name = "joystickButton13", layout = "Button", bit = 28u)]
		[InputControl(name = "joystickButton14", layout = "Button", bit = 29u)]
		[InputControl(name = "joystickButton15", layout = "Button", bit = 30u)]
		[InputControl(name = "joystickButton16", layout = "Button", bit = 31u)]
		public int bits4;

		[InputControl(name = "joystickButton17", layout = "Button", bit = 0u)]
		[InputControl(name = "joystickButton18", layout = "Button", bit = 1u)]
		[InputControl(name = "joystickButton19", layout = "Button", bit = 2u)]
		[InputControl(name = "joystick1Button0", layout = "Button", bit = 3u)]
		[InputControl(name = "joystick1Button1", layout = "Button", bit = 4u)]
		[InputControl(name = "joystick1Button2", layout = "Button", bit = 5u)]
		[InputControl(name = "joystick1Button3", layout = "Button", bit = 6u)]
		[InputControl(name = "joystick1Button4", layout = "Button", bit = 7u)]
		[InputControl(name = "joystick1Button5", layout = "Button", bit = 8u)]
		[InputControl(name = "joystick1Button6", layout = "Button", bit = 9u)]
		[InputControl(name = "joystick1Button7", layout = "Button", bit = 10u)]
		[InputControl(name = "joystick1Button8", layout = "Button", bit = 11u)]
		[InputControl(name = "joystick1Button9", layout = "Button", bit = 12u)]
		[InputControl(name = "joystick1Button10", layout = "Button", bit = 13u)]
		[InputControl(name = "joystick1Button11", layout = "Button", bit = 14u)]
		[InputControl(name = "joystick1Button12", layout = "Button", bit = 15u)]
		[InputControl(name = "joystick1Button13", layout = "Button", bit = 16u)]
		[InputControl(name = "joystick1Button14", layout = "Button", bit = 17u)]
		[InputControl(name = "joystick1Button15", layout = "Button", bit = 18u)]
		[InputControl(name = "joystick1Button16", layout = "Button", bit = 19u)]
		[InputControl(name = "joystick1Button17", layout = "Button", bit = 20u)]
		[InputControl(name = "joystick1Button18", layout = "Button", bit = 21u)]
		[InputControl(name = "joystick1Button19", layout = "Button", bit = 22u)]
		[InputControl(name = "joystick2Button0", layout = "Button", bit = 23u)]
		[InputControl(name = "joystick2Button1", layout = "Button", bit = 24u)]
		[InputControl(name = "joystick2Button2", layout = "Button", bit = 25u)]
		[InputControl(name = "joystick2Button3", layout = "Button", bit = 26u)]
		[InputControl(name = "joystick2Button4", layout = "Button", bit = 27u)]
		[InputControl(name = "joystick2Button5", layout = "Button", bit = 28u)]
		[InputControl(name = "joystick2Button6", layout = "Button", bit = 29u)]
		[InputControl(name = "joystick2Button7", layout = "Button", bit = 30u)]
		[InputControl(name = "joystick2Button8", layout = "Button", bit = 31u)]
		public int bits5;

		[InputControl(name = "joystick2Button9", layout = "Button", bit = 0u)]
		[InputControl(name = "joystick2Button10", layout = "Button", bit = 1u)]
		[InputControl(name = "joystick2Button11", layout = "Button", bit = 2u)]
		[InputControl(name = "joystick2Button12", layout = "Button", bit = 3u)]
		[InputControl(name = "joystick2Button13", layout = "Button", bit = 4u)]
		[InputControl(name = "joystick2Button14", layout = "Button", bit = 5u)]
		[InputControl(name = "joystick2Button15", layout = "Button", bit = 6u)]
		[InputControl(name = "joystick2Button16", layout = "Button", bit = 7u)]
		[InputControl(name = "joystick2Button17", layout = "Button", bit = 8u)]
		[InputControl(name = "joystick2Button18", layout = "Button", bit = 9u)]
		[InputControl(name = "joystick2Button19", layout = "Button", bit = 10u)]
		[InputControl(name = "joystick3Button0", layout = "Button", bit = 11u)]
		[InputControl(name = "joystick3Button1", layout = "Button", bit = 12u)]
		[InputControl(name = "joystick3Button2", layout = "Button", bit = 13u)]
		[InputControl(name = "joystick3Button3", layout = "Button", bit = 14u)]
		[InputControl(name = "joystick3Button4", layout = "Button", bit = 15u)]
		[InputControl(name = "joystick3Button5", layout = "Button", bit = 16u)]
		[InputControl(name = "joystick3Button6", layout = "Button", bit = 17u)]
		[InputControl(name = "joystick3Button7", layout = "Button", bit = 18u)]
		[InputControl(name = "joystick3Button8", layout = "Button", bit = 19u)]
		[InputControl(name = "joystick3Button9", layout = "Button", bit = 20u)]
		[InputControl(name = "joystick3Button10", layout = "Button", bit = 21u)]
		[InputControl(name = "joystick3Button11", layout = "Button", bit = 22u)]
		[InputControl(name = "joystick3Button12", layout = "Button", bit = 23u)]
		[InputControl(name = "joystick3Button13", layout = "Button", bit = 24u)]
		[InputControl(name = "joystick3Button14", layout = "Button", bit = 25u)]
		[InputControl(name = "joystick3Button15", layout = "Button", bit = 26u)]
		[InputControl(name = "joystick3Button16", layout = "Button", bit = 27u)]
		[InputControl(name = "joystick3Button17", layout = "Button", bit = 28u)]
		[InputControl(name = "joystick3Button18", layout = "Button", bit = 29u)]
		[InputControl(name = "joystick3Button19", layout = "Button", bit = 30u)]
		[InputControl(name = "joystick4Button0", layout = "Button", bit = 31u)]
		public int bits6;

		[InputControl(name = "joystick4Button1", layout = "Button", bit = 0u)]
		[InputControl(name = "joystick4Button2", layout = "Button", bit = 1u)]
		[InputControl(name = "joystick4Button3", layout = "Button", bit = 2u)]
		[InputControl(name = "joystick4Button4", layout = "Button", bit = 3u)]
		[InputControl(name = "joystick4Button5", layout = "Button", bit = 4u)]
		[InputControl(name = "joystick4Button6", layout = "Button", bit = 5u)]
		[InputControl(name = "joystick4Button7", layout = "Button", bit = 6u)]
		[InputControl(name = "joystick4Button8", layout = "Button", bit = 7u)]
		[InputControl(name = "joystick4Button9", layout = "Button", bit = 8u)]
		[InputControl(name = "joystick4Button10", layout = "Button", bit = 9u)]
		[InputControl(name = "joystick4Button11", layout = "Button", bit = 10u)]
		[InputControl(name = "joystick4Button12", layout = "Button", bit = 11u)]
		[InputControl(name = "joystick4Button13", layout = "Button", bit = 12u)]
		[InputControl(name = "joystick4Button14", layout = "Button", bit = 13u)]
		[InputControl(name = "joystick4Button15", layout = "Button", bit = 14u)]
		[InputControl(name = "joystick4Button16", layout = "Button", bit = 15u)]
		[InputControl(name = "joystick4Button17", layout = "Button", bit = 16u)]
		[InputControl(name = "joystick4Button18", layout = "Button", bit = 17u)]
		[InputControl(name = "joystick4Button19", layout = "Button", bit = 18u)]
		[InputControl(name = "joystick5Button0", layout = "Button", bit = 19u)]
		[InputControl(name = "joystick5Button1", layout = "Button", bit = 20u)]
		[InputControl(name = "joystick5Button2", layout = "Button", bit = 21u)]
		[InputControl(name = "joystick5Button3", layout = "Button", bit = 22u)]
		[InputControl(name = "joystick5Button4", layout = "Button", bit = 23u)]
		[InputControl(name = "joystick5Button5", layout = "Button", bit = 24u)]
		[InputControl(name = "joystick5Button6", layout = "Button", bit = 25u)]
		[InputControl(name = "joystick5Button7", layout = "Button", bit = 26u)]
		[InputControl(name = "joystick5Button8", layout = "Button", bit = 27u)]
		[InputControl(name = "joystick5Button9", layout = "Button", bit = 28u)]
		[InputControl(name = "joystick5Button10", layout = "Button", bit = 29u)]
		[InputControl(name = "joystick5Button11", layout = "Button", bit = 30u)]
		[InputControl(name = "joystick5Button12", layout = "Button", bit = 31u)]
		public int bits7;

		[InputControl(name = "joystick5Button13", layout = "Button", bit = 0u)]
		[InputControl(name = "joystick5Button14", layout = "Button", bit = 1u)]
		[InputControl(name = "joystick5Button15", layout = "Button", bit = 2u)]
		[InputControl(name = "joystick5Button16", layout = "Button", bit = 3u)]
		[InputControl(name = "joystick5Button17", layout = "Button", bit = 4u)]
		[InputControl(name = "joystick5Button18", layout = "Button", bit = 5u)]
		[InputControl(name = "joystick5Button19", layout = "Button", bit = 6u)]
		[InputControl(name = "joystick6Button0", layout = "Button", bit = 7u)]
		[InputControl(name = "joystick6Button1", layout = "Button", bit = 8u)]
		[InputControl(name = "joystick6Button2", layout = "Button", bit = 9u)]
		[InputControl(name = "joystick6Button3", layout = "Button", bit = 10u)]
		[InputControl(name = "joystick6Button4", layout = "Button", bit = 11u)]
		[InputControl(name = "joystick6Button5", layout = "Button", bit = 12u)]
		[InputControl(name = "joystick6Button6", layout = "Button", bit = 13u)]
		[InputControl(name = "joystick6Button7", layout = "Button", bit = 14u)]
		[InputControl(name = "joystick6Button8", layout = "Button", bit = 15u)]
		[InputControl(name = "joystick6Button9", layout = "Button", bit = 16u)]
		[InputControl(name = "joystick6Button10", layout = "Button", bit = 17u)]
		[InputControl(name = "joystick6Button11", layout = "Button", bit = 18u)]
		[InputControl(name = "joystick6Button12", layout = "Button", bit = 19u)]
		[InputControl(name = "joystick6Button13", layout = "Button", bit = 20u)]
		[InputControl(name = "joystick6Button14", layout = "Button", bit = 21u)]
		[InputControl(name = "joystick6Button15", layout = "Button", bit = 22u)]
		[InputControl(name = "joystick6Button16", layout = "Button", bit = 23u)]
		[InputControl(name = "joystick6Button17", layout = "Button", bit = 24u)]
		[InputControl(name = "joystick6Button18", layout = "Button", bit = 25u)]
		[InputControl(name = "joystick6Button19", layout = "Button", bit = 26u)]
		[InputControl(name = "joystick7Button0", layout = "Button", bit = 27u)]
		[InputControl(name = "joystick7Button1", layout = "Button", bit = 28u)]
		[InputControl(name = "joystick7Button2", layout = "Button", bit = 29u)]
		[InputControl(name = "joystick7Button3", layout = "Button", bit = 30u)]
		[InputControl(name = "joystick7Button4", layout = "Button", bit = 31u)]
		public int bits8;

		[InputControl(name = "joystick7Button5", layout = "Button", bit = 0u)]
		[InputControl(name = "joystick7Button6", layout = "Button", bit = 1u)]
		[InputControl(name = "joystick7Button7", layout = "Button", bit = 2u)]
		[InputControl(name = "joystick7Button8", layout = "Button", bit = 3u)]
		[InputControl(name = "joystick7Button9", layout = "Button", bit = 4u)]
		[InputControl(name = "joystick7Button10", layout = "Button", bit = 5u)]
		[InputControl(name = "joystick7Button11", layout = "Button", bit = 6u)]
		[InputControl(name = "joystick7Button12", layout = "Button", bit = 7u)]
		[InputControl(name = "joystick7Button13", layout = "Button", bit = 8u)]
		[InputControl(name = "joystick7Button14", layout = "Button", bit = 9u)]
		[InputControl(name = "joystick7Button15", layout = "Button", bit = 10u)]
		[InputControl(name = "joystick7Button16", layout = "Button", bit = 11u)]
		[InputControl(name = "joystick7Button17", layout = "Button", bit = 12u)]
		[InputControl(name = "joystick7Button18", layout = "Button", bit = 13u)]
		[InputControl(name = "joystick7Button19", layout = "Button", bit = 14u)]
		[InputControl(name = "joystick8Button0", layout = "Button", bit = 15u)]
		[InputControl(name = "joystick8Button1", layout = "Button", bit = 16u)]
		[InputControl(name = "joystick8Button2", layout = "Button", bit = 17u)]
		[InputControl(name = "joystick8Button3", layout = "Button", bit = 18u)]
		[InputControl(name = "joystick8Button4", layout = "Button", bit = 19u)]
		[InputControl(name = "joystick8Button5", layout = "Button", bit = 20u)]
		[InputControl(name = "joystick8Button6", layout = "Button", bit = 21u)]
		[InputControl(name = "joystick8Button7", layout = "Button", bit = 22u)]
		[InputControl(name = "joystick8Button8", layout = "Button", bit = 23u)]
		[InputControl(name = "joystick8Button9", layout = "Button", bit = 24u)]
		[InputControl(name = "joystick8Button10", layout = "Button", bit = 25u)]
		[InputControl(name = "joystick8Button11", layout = "Button", bit = 26u)]
		[InputControl(name = "joystick8Button12", layout = "Button", bit = 27u)]
		[InputControl(name = "joystick8Button13", layout = "Button", bit = 28u)]
		[InputControl(name = "joystick8Button14", layout = "Button", bit = 29u)]
		[InputControl(name = "joystick8Button15", layout = "Button", bit = 30u)]
		[InputControl(name = "joystick8Button16", layout = "Button", bit = 31u)]
		public int bits9;

		[InputControl(name = "joystick8Button17", layout = "Button", bit = 0u)]
		[InputControl(name = "joystick8Button18", layout = "Button", bit = 1u)]
		[InputControl(name = "joystick8Button19", layout = "Button", bit = 2u)]
		public int bits10;

		public FourCC format => default(FourCC);

		public void Update()
		{
		}
	}
}
